### ISSUE TITLE
5DPrint Alpha-V2 can't be built given current README instructions

### ISSUE THREAD

**Issue by NarimaanV** [Makible/5DPrint#1]
![screen shot 2013-10-10 at 8 45 37 pm](https://f.cloud.github.com/assets/4958838/1318399/244b70ca-32bb-11e3-8997-86f70f7512e8.png)

**Comment by elliottpolk** [comment]
Hmmm.. I unfortunately have not see that issue. My apologies for a late response on this. Since this has been created, we've moved off the Go version for now and are using a Chrome App instead. I'd advise looking into that to begin with. 

From here, we'll be patching the Go version for later use. Feel free to fork what we have and work from there, if you'd like.
